import type { SeedLocation } from "../../types/raftoff";

/**
 * Lake St. Clair launch registry (deployment PDF §6).
 * coordinates remain null until manually verified — do not invent GPS.
 * schematic x/y are UI-only anchors on the dark map (0–1), not real world coords.
 */
const locations: SeedLocation[] = [
  // A. Social destinations
  { slug: "strawberry-island", name: "Strawberry Island / Sandbar", type: "social_sandbar", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", regionHint: "Anchor Bay", defaultVibes: ["party", "chill", "family"], supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.42, y: 0.28 } },
  { slug: "gull-island", name: "Gull Island", type: "social_island", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", regionHint: "St. Clair Flats", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.62, y: 0.48 } },
  { slug: "muscamoot-bay", name: "Muscamoot Bay", type: "social_bay", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", regionHint: "Harsens Island", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.68, y: 0.42 } },
  { slug: "little-muscamoot-bay", name: "Little Muscamoot Bay", type: "social_bay", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.7, y: 0.46 } },
  { slug: "grassy-bends", name: "Grassy / Grassy Bends", type: "social_sandbar", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.55, y: 0.4 } },
  { slug: "jobbie-nooner-zone", name: "Jobbie Nooner Zone", type: "event_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", regionHint: "Gull Island event area", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.64, y: 0.5 } },
  { slug: "big-muscamoot-goose-bay", name: "Big Muscamoot / Goose Bay", type: "social_bay", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.72, y: 0.44 } },
  { slug: "metro-beach-offshore", name: "Metro Beach offshore anchoring", type: "social_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.38, y: 0.58 } },
  { slug: "new-baltimore-waterfront", name: "New Baltimore / Anchor Bay waterfront", type: "social_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.48, y: 0.22 } },
  { slug: "belle-river-anchoring", name: "Belle River / south-shore anchoring", type: "social_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "A", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.58, y: 0.72 } },

  // B. Regions / channels (labels; schematic for map labels)
  { slug: "anchor-bay", name: "Anchor Bay", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsCheckIn: false, supportsLocationFeed: true }, schematic: { x: 0.4, y: 0.25 } },
  { slug: "main-lake", name: "Lake St. Clair Main Lake", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.5, y: 0.5 } },
  { slug: "st-clair-flats", name: "St. Clair Flats", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.66, y: 0.45 } },
  { slug: "harsens-island", name: "Harsens Island", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.74, y: 0.38 } },
  { slug: "dickinson-island", name: "Dickinson Island", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.7, y: 0.52 } },
  { slug: "walpole-island-area", name: "Walpole Island area", type: "region", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", regionHint: "Respect Canadian/First Nation boundaries", supportsLocationFeed: true }, schematic: { x: 0.78, y: 0.48 } },
  { slug: "north-channel", name: "North Channel", type: "channel", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.72, y: 0.34 } },
  { slug: "middle-channel", name: "Middle Channel", type: "channel", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.7, y: 0.4 } },
  { slug: "south-channel", name: "South Channel", type: "channel", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.68, y: 0.55 } },
  { slug: "chenal-ecarte", name: "Chenal Ecarte", type: "channel", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.76, y: 0.42 } },
  { slug: "clinton-river-mouth", name: "Clinton River Mouth", type: "channel_mouth", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.32, y: 0.52 } },
  { slug: "black-creek-metropark", name: "Black Creek / Metropark basin", type: "channel_mouth", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.34, y: 0.56 } },
  { slug: "detroit-river-entrance", name: "Detroit River entrance", type: "channel_mouth", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "B", supportsLocationFeed: true }, schematic: { x: 0.28, y: 0.78 } },

  // C. Parks / beaches
  { slug: "lake-st-clair-metropark", name: "Lake St. Clair Metropark", type: "park", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.36, y: 0.55 } },
  { slug: "metropark-north-marina", name: "Metropark North Marina / boat basin", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.35, y: 0.53 } },
  { slug: "burke-park-new-baltimore", name: "Walter and Mary Burke Park", type: "park", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.5, y: 0.2 } },
  { slug: "brandenburg-park", name: "Brandenburg Park waterfront", type: "park", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.52, y: 0.24 } },
  { slug: "nautical-mile", name: "St. Clair Shores Nautical Mile", type: "waterfront_district", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.3, y: 0.62 } },
  { slug: "belle-isle-shoreline", name: "Belle Isle shoreline/launch area", type: "park", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.26, y: 0.82 } },
  { slug: "windsor-waterfront", name: "Windsor waterfront", type: "waterfront_district", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "C", supportsLocationFeed: true }, schematic: { x: 0.34, y: 0.84 } },

  // D. Launches
  { slug: "selfridge-dnr", name: "Selfridge DNR Boating Access Site", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.44, y: 0.34 } },
  { slug: "harley-ensign-dnr", name: "Harley Ensign Memorial DNR Access", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.46, y: 0.36 } },
  { slug: "clinton-river-cutoff-dnr", name: "Clinton River Cut-Off DNR Access", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.33, y: 0.5 } },
  { slug: "metropark-boat-launch", name: "Lake St. Clair Metropark Boat Launch", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.37, y: 0.57 } },
  { slug: "algonac-dnr", name: "Algonac DNR / North Channel launch", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.8, y: 0.32 } },
  { slug: "fair-haven-dnr", name: "Fair Haven DNR Boating Access Site", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.58, y: 0.3 } },
  { slug: "scs-9-mile-ramp", name: "St. Clair Shores 9 Mile Boat Ramp", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", publicAccess: true, supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.29, y: 0.64 } },
  { slug: "blossom-heath-ramp", name: "Blossom Heath Boat Ramp", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", residentOnly: true, supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.31, y: 0.6 } },
  { slug: "lac-st-clair-ramp", name: "Lac St. Clair Boat Ramp", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", residentOnly: true, supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.3, y: 0.66 } },
  { slug: "riverside-marina-launch", name: "Riverside Marina / Detroit River launch", type: "boat_launch", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "D", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.27, y: 0.8 } },

  // E. Marinas
  { slug: "tashmoo-marina", name: "Tashmoo Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.76, y: 0.36 } },
  { slug: "mayea-marina", name: "Mayea Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.77, y: 0.4 } },
  { slug: "northpointe-shores-marina", name: "Northpointe Shores Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.54, y: 0.26 } },
  { slug: "bouvier-bridge-marina", name: "Bouvier Bridge Marina / resort", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.6, y: 0.28 } },
  { slug: "belle-river-marina", name: "Belle River Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.6, y: 0.74 } },
  { slug: "st-clair-boat-harbor", name: "St. Clair Boat Harbor", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.82, y: 0.28 } },
  { slug: "jefferson-beach-marina", name: "Jefferson Beach Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.32, y: 0.68 } },
  { slug: "macray-harbor", name: "MacRay Harbor", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.45, y: 0.32 } },
  { slug: "belle-maer-harbor", name: "Belle Maer Harbor", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.43, y: 0.38 } },
  { slug: "hideaway-harbor", name: "Hideaway Harbor", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.56, y: 0.34 } },
  { slug: "michigan-harbor", name: "Michigan Harbor", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.34, y: 0.7 } },
  { slug: "markley-marine", name: "Markley Marine", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.33, y: 0.72 } },
  { slug: "keans-marina", name: "Kean's Marina", type: "marina", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "E", supportsCheckIn: true, supportsLocationFeed: true }, schematic: { x: 0.28, y: 0.76 } },

  // F. Fishing zones (broad, privacy-safe)
  { slug: "anchor-bay-fishing", name: "Anchor Bay fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.44, y: 0.3 } },
  { slug: "selfridge-mile-roads-fishing", name: "Selfridge / northern Mile Roads fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.4, y: 0.4 } },
  { slug: "metropark-huron-point-fishing", name: "Metropark / Huron Point fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.38, y: 0.54 } },
  { slug: "scs-mile-roads-fishing", name: "St. Clair Shores Mile Roads fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.31, y: 0.63 } },
  { slug: "grosse-pointe-fishing", name: "Grosse Pointe shoreline fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.3, y: 0.74 } },
  { slug: "flats-channel-fishing", name: "St. Clair Flats channel fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.67, y: 0.47 } },
  { slug: "belle-river-ontario-fishing", name: "Belle River / Ontario shore fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.57, y: 0.7 } },
  { slug: "thames-river-mouth-fishing", name: "Thames River mouth general fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.65, y: 0.68 } },
  { slug: "detroit-river-mouth-fishing", name: "Detroit River mouth fishing zone", type: "fishing_zone", coordinates: null, boundaryGeoJson: null, verificationStatus: "needs_review", sourceUrl: null, attributes: { group: "F", supportsLocationFeed: true }, schematic: { x: 0.29, y: 0.79 } },
];

export default locations;
